#!/bin/bash
set -e

source $(dirname $0)/version

cd $(dirname $0)/..

mkdir -p bin
LINKFLAGS="-s -w"
CGO_ENABLED=0 go build -tags netgo -ldflags "-X main.VERSION=$VERSION $LINKFLAGS" -o bin/lb-controller
