#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${script_dir}/version"

cd "${script_dir}/.."

mkdir -p bin
LINKFLAGS="-s -w"
CGO_ENABLED=0 go build -trimpath -tags netgo \
    -ldflags "-buildid= -X main.VERSION=$VERSION $LINKFLAGS" \
    -o bin/lb-controller
