#!/bin/bash
set -e

ARCH=${ARCH:?"ARCH not set"}
SUFFIX=""
[ "${ARCH}" != "amd64" ] && SUFFIX="_${ARCH}"

source $(dirname $0)/version

cd $(dirname $0)/../package
mkdir -p ../dist

TAG=${TAG:-${VERSION}${SUFFIX}}
REPO=${REPO:-ghcr.io/chen21019}
IMAGE_PREFIX=${IMAGE_PREFIX:-rc16-}

if [ ! -e ../bin/lb-controller ]; then
    ../scripts/build
fi

echo "" > ../dist/images

for dir in */
do
    cd "${dir}"
    provider_type=${dir%/}
    cp ../../bin/lb-controller .
    rm -rf scripts config
    cp -r ../../provider/${provider_type}/scripts .
    cp -r ../../provider/${provider_type}/config .
    IMAGE=${REPO}/${IMAGE_PREFIX}lb-service-${provider_type}:${TAG}
    DOCKER_BUILDKIT="${DOCKER_BUILDKIT:-0}" docker build \
        --network "${DOCKER_BUILD_NETWORK:-host}" \
        --build-arg UBUNTU_MIRROR="${UBUNTU_MIRROR:-http://archive.ubuntu.com/ubuntu}" \
        -t "${IMAGE}" .
    echo ${IMAGE} >> ../../dist/images
    echo Built ${IMAGE}
    cd ..
done
