#!/bin/bash
set -e

ARCH=${ARCH:?"ARCH not set"}
SUFFIX=""
[ "${ARCH}" != "amd64" ] && SUFFIX="_${ARCH}"

source $(dirname $0)/version

cd $(dirname $0)/../package
mkdir -p ../dist

TAG=${TAG:-${VERSION}${SUFFIX}}
REPO=${REPO:-ghcr.io/pasturestack}
IMAGE_PREFIX=${IMAGE_PREFIX:-}
SOURCE_REVISION=${SOURCE_REVISION:-$(git rev-parse HEAD)}

if [ ! -e ../bin/lb-controller ]; then
    ../scripts/build
fi

echo "" > ../dist/images

for dir in */
do
    cd "${dir}"
    provider_type=${dir%/}
    cp ../../bin/lb-controller .
    rm -rf scripts config
    cp -r ../../provider/${provider_type}/scripts .
    cp -r ../../provider/${provider_type}/config .
    case "${provider_type}" in
        haproxy) image_name=load-balancer-service ;;
        rancher) image_name=load-balancer-controller-sidecar ;;
        *) image_name=load-balancer-service-${provider_type} ;;
    esac
    IMAGE=${REPO}/${IMAGE_PREFIX}${image_name}:${TAG}
    DOCKER_BUILDKIT="${DOCKER_BUILDKIT:-0}" docker build \
        --network "${DOCKER_BUILD_NETWORK:-host}" \
        --build-arg UBUNTU_MIRROR="${UBUNTU_MIRROR:-http://archive.ubuntu.com/ubuntu}" \
        --build-arg RC16_IMAGE_VERSION="${TAG}" \
        --build-arg SOURCE_REVISION="${SOURCE_REVISION}" \
        -t "${IMAGE}" .
    echo ${IMAGE} >> ../../dist/images
    echo Built ${IMAGE}
    cd ..
done
