#!/usr/bin/env bash
set -euo pipefail

root_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "${root_dir}"

race_flag=()
if [[ "${ARCH:-amd64}" == "amd64" ]]; then
    race_flag=(-race)
fi
go test -mod=vendor "${race_flag[@]}" -cover -tags=test ./...
